channel:
  - r
  - arcgis
  - conda-forge
dependencies:
  - r-base
  - r-essentials
  - r-tidyverse
  - r-sf
  - r-ggspatial
  - r-osrm
  - r-tidygeocoder
  - r-tmap
  - r-devtools
  - r-rgeos
  - r-ggplot2
